### ISSUE TITLE
Adding addition file extention

### ISSUE THREAD

**Issue by jmohler1970** [atuttle/atom-language-cfml#102]
I regularly have ColdFusion files with a `*.cfi` name.

I do this for files that must only be used as an include and never directly ran.

Is there a way to have syntax highlighting for that extension?

**Comment by jmohler1970** [comment]
Just found it:

lib/languageCFML.js on line 32 needs to read: 

```java
} else if (editor.getURI().endsWith("cfm") || editor.getURI().endsWith("cfml") || editor.getURI().endsWith("cfi")) {
```

**Comment by atuttle** [comment]
Is this a standard practice? First I've ever heard of it.

**Comment by KamasamaK** [comment]
I don't believe that is standard practice. You can edit your `config.cson` like so to accomplish your recommended change:

```
core:
  customFileTypes:
    'text.html.cfml': [
      'cfi'
    ]
```

**Comment by David-Polehonski** [comment]
I would agree with @KamasamaK this would be a local configuration rather than a plugin update. Shall we mark this issue as closed?

**Comment by atuttle** [comment]
Sounds like the right solution to me.

**Comment by jmohler1970** [comment]
Good for me
