### ISSUE TITLE
Nested Comments breaks highlighting

### ISSUE THREAD

**Issue by paologroppo** [atuttle/atom-language-cfml#104]
Nested Comments breaks highlighting.
Example:
\ --->

![schermata 2017-05-04 alle 12 16 32](https://cloud.githubusercontent.com/assets/6460823/25699498/ccdc88a0-30c3-11e7-88f2-a4968e8ceb44.png)

**Comment by David-Polehonski** [comment]
I have a fix for this; but it's tied up with some other development. If that's acceptable then I'll open a pull request. It also addresses #83 and #103
