### ISSUE TITLE
Code Completion

### ISSUE THREAD

**Issue by 41GitHub** [atuttle/atom-language-cfml#11]
Is there a way to get cfml code completion? Or do you just need to have file open in another buffer?

**Comment by David-Polehonski** [comment]
The snippets files offer a significant amount of code completion for CF Tags, and functions. If you feel they are missing any definitions you can add them.

**Comment by atuttle** [comment]
@David-Polehonski I believe what @41GitHub is asking for is, for example, variable names in their code to show up as completion options. Sublime does this (or one of the plugins I use with Sublime, at least).

I don't think it's something we can control from our plugin -- and if it is, I don't think it's something we're likely to take on. It sounds like a _big_ job. I'm going to close this issue as wont-fix, but that decision is **not final**. If anyone finds a solution, go ahead and post it and we can re-evaluate.
