### ISSUE TITLE
Not recognizing CFCs

### ISSUE THREAD

**Issue by benjadock** [atuttle/atom-language-cfml#114]
With the new update of Atom 1.24.0, I am no longer able to get highlighting on CFC files. If I change it to be a CFM, then it works.

Thanks!

-Ben

EDIT: Just like infernocloud, I am unable to scroll the entire file.

**Comment by infernocloud** [comment]
I am seeing the same problem. It also makes it impossible to scroll through a .cfc file until the atom-language-cfml is disabled. It will constantly bounce scroll position to the default spot.

**Comment by infernocloud** [comment]
#109

**Comment by Miguel-F** [comment]
I am experiencing both of these issues as well.  On the scrolling issue, it will not allow you to scroll down beyond the current cursor position when using the mouse scroll wheel.  Using the keyboard (page-up/page-down, arrows) does seem to work normally.

**Comment by David-Polehonski** [comment]
If @benjadock  or @Miguel-F could confirm the latest patches have resolved this issue we can close it.

**Comment by benjadock** [comment]
Just uninstalled and then reinstalled the plugin, it's working as it should.

Thank you!

**Comment by Miguel-F** [comment]
I updated via the package manager in Atom.  Everything is working correctly.  Thanks so much for the quick fix on this.

**Comment by JessicaOPRD** [comment]
Thanks everyone for posting about this issue and for the quick turnaround. Much appreciated!
