### ISSUE TITLE
Multi-line Comments Broken

### ISSUE THREAD

**Issue by jorabyte** [atuttle/atom-language-cfml#119]
After a recent update to version 0.23.0 I've noticed tags in multi-line comments in .cfm files are not syntax-highlighted as comments.  Disabling language-cfml and restarting Atom fixes the comment highlighting (apparently the built-in language-html detects CFML tags now).  I have to re-enable language-cfml for .cfc files to be syntax-highlighted.

![image](https://user-images.githubusercontent.com/2533066/38277060-bc28fcbe-375c-11e8-83f7-4b78510dfec4.png)

**Comment by David-Polehonski** [comment]
Does the code in the screenshot predictably fail? could you produce a minimum fail case for me to test against?

**Comment by jorabyte** [comment]
I uninstalled / reinstalled the package (same version) and the code in the screenshot seems to not fail anymore in a new file.  However, you have a new issue report, [Syntax Coloring Fails #120](https://github.com/atuttle/atom-language-cfml/issues/120), that seems to match the behavior I'm seeing.

If I disable this package and restart Atom, .cfm files are for the most part syntax highlighted correctly, **aside from functions being plain white**.  CFCs are not highlighted without your package.  Re-enabling or re-installing language-cfml results in CFCs being highlighted, but .cfm syntax highlighting is broken in various places.

It's hard for me to give you repeatable test cases, so I would suggest closing this ticket and focusing on #120.  Thanks for your quick follow-up.

**Comment by David-Polehonski** [comment]
I'll be getting to around to issue #120 asap; if you open a file and the highlighting is failing, try ctrl + shift + f5, it restarts atom and the highlighting kicks back in.. not sure why, yet.

**Comment by jorabyte** [comment]
@David-Polehonski you're the greatest!  I don't imagine you're getting paid (or not enough if you are) to maintain this, so you have this poor programmer's gratitude, positive vibes sent your way.

FYI Ctrl+Shift+F5 doesn't restart Atom for me; when I close or restart I usually have to close the app twice. Maybe I'm using a troublesome plugin.

I will attach some screenshots to #120 to show you what I'm experiencing in case it's relevant and helpful.
