### ISSUE TITLE
Using the new in HTML breaks

### ISSUE THREAD

**Issue by pfreitag** [atuttle/atom-language-cfml#20]
If you use the word new in some HTML it thinks it is the new keyword and breaks color coding for the remainder of the document. For example:
    `<p>This is new ohno</p>`

**Comment by TheFlyingFish** [comment]
Also experiencing this issue.  I think it's the same root issue as #10.

**Comment by David-Polehonski** [comment]
This issue should be fixed as of version 0.8.0
