### ISSUE TITLE
How to install on Atom 1.0?

### ISSUE THREAD

**Issue by coke** [atuttle/atom-language-cfml#26]
This package isn't listed on the atom.io listing, so I can't install it via atom's GUI. I tried installing the atom command line tools, but can't find an invocation of apm that will install from the command line (did a git clone and cd'd to it, "apm install ." claims to work, but doesn't appear to install anything.)

**Comment by atuttle** [comment]
https://atom.io/packages/language-cfml :question:

**Comment by coke** [comment]
Blargh. It's probably a proxy issue. I saw many languages under "Settings -> Packages", but not cfml (now realize those are installed).

If I go to Install, then search for cfml, I get "getaddrinfo ENOTFOUND", which probably means it's ignoring my http proxy.

Sorry for the noise.
