### ISSUE TITLE
Backslash in string confuses highlighter

### ISSUE THREAD

**Issue by coke** [atuttle/atom-language-cfml#27]
Tried this in CF 10 -

```
<cfscript>
    a = "\";
    WriteDump(a);
</cfscript>
```

atom-language-cfml thinks that the string never ends (while the CF engine prints out a single backslash). Looks like it correctly handles the literal string ````""""````

**Comment by dttripler** [comment]
This is now happening in cfset and cfif tags.
```
<cfset exportDirectory = "\">
```
```
<cfif "" neq "\">

</cfif>
```

**Comment by infernocloud** [comment]
Just wanted to put my vote in for this one too. It's the only "show-stopper" bug with this package for me.

**Comment by tollus** [comment]
pull request #44 fixed this for me
