### ISSUE TITLE
No HTML syntax highlighting in CFM files

### ISSUE THREAD

**Issue by LoganHollins** [atuttle/atom-language-cfml#30]
In the new 0.8.0 release HTML syntax isn't highlighted.

**Comment by tollus** [comment]
Looks like it's because the default syntax is now cfscript instead of "CFML" or "CFML (HTML)".

**Comment by atuttle** [comment]
@David-Polehonski Looks like a regression from #28.

**Comment by tollus** [comment]
a simple change for me, was to just rename "cfml" to "CFML". (line 2 in cfml.cson)

I don't understand why that worked...

**Comment by David-Polehonski** [comment]
The HTML (CFML) Mode includes the embedded HTML. I'm not sure how the default for a particular file extension is set though?

**Comment by clintconklin** [comment]
I'm seeing this as well, even in my brand spanking new update of 0.8.2.

**Comment by ArtskydJ** [comment]
I had this issue in `0.8.2` and reverted to `0.7.1`.

**Comment by zephraph** [comment]
This is fixed by #30, confirmed in 0.8.3.
