### ISSUE TITLE
New mixed mode (HTML (CFML)) uses HTML comments instead of CFML comments 

### ISSUE THREAD

**Issue by zephraph** [atuttle/atom-language-cfml#37]
The newly released mixed mode uses ```<!--``` ```-->``` for comments instead of the appropriate CFML ```<!---``` three dash equivalent. 

This applies to v0.8.3.

**Comment by dajester2013** [comment]
settings/language-cfml.cson references text.html.cfm, not text.html.cfml

**Comment by atuttle** [comment]
Merged #38 and published.
