### ISSUE TITLE
Doesn't recognize closing CFML comment tags <!--- --->

### ISSUE THREAD

**Issue by bodenlos** [atuttle/atom-language-cfml#4]
Syntax highlighting responds correctly to (closing) HTML comment tags 
    
but not CFML comment tags (with an extra dash on open and close)
    

Instead all lines following a closing CFML tag (until the next HTML comment close) are greyed out as if part of a comment.

**Comment by vladware** [comment]
I think it's other special characters breaking it.
![capture](https://cloud.githubusercontent.com/assets/11525288/6693324/99af4534-cca8-11e4-9b0b-2b971471b033.PNG)
