### ISSUE TITLE
Highlighting gets stuck when opening multiple cfc files

### ISSUE THREAD

**Issue by ArtskydJ** [atuttle/atom-language-cfml#40]
Using version `0.8.4`.

If I open `script.cfc`...
```cfc
component {
    public function init() {
        // ...
    }
}
```
...and then I open `tags.cfc`...
```html
<cfcomponent>
    <cffunction name="init" access="public">
        <!-- ... -->
    </cffunction>
<cfcomponent>
```
...then `tags.cfc` does not highlight correctly.

If I close and open atom, and then open `tags.cfc` and then `script.cfc`, then `script.cfc` does not highlight correctly.

Whichever one is opened first highlights correctly, but it seems to get stuck in that mode.

**Comment by dajester2013** [comment]
I've had that problem occasionally after pulling updates to the package.  As a workaround, can you try running `apm rebuild-module-cache` and see if that fixes it for you? You may need to reload atom after running that command.

**Comment by ArtskydJ** [comment]
@dajester2013 Thanks, that fixed the issue!
