### ISSUE TITLE
CFML within in-page JavaScript does not get syntax highlighting

### ISSUE THREAD

**Issue by ndguardian** [atuttle/atom-language-cfml#45]
On CFML pages that have JavaScript in them, if there are CFML tags within the JavaScript, they do not get CFML syntax highlighting. It is colored solely as JavaScript. Is there any way to resolve this? Please let me know if there is anything I can do to help!

**Comment by atuttle** [comment]
The best thing to do, if you can, is to write a failing test case for the issue you are seeing.  You can look at[ our own spec folder](https://github.com/atuttle/atom-language-cfml/tree/master/spec) for this and also on the [Atom documentation](https://atom.io/docs/v1.0.19/hacking-atom-writing-specs).  This will help those maintaining this package know precisely what is broken.

**Comment by elpete** [comment]
Fixed in 0.12
