### ISSUE TITLE
Code completion generates <<cfsometag ...

### ISSUE THREAD

**Issue by Ratcreamsoup** [atuttle/atom-language-cfml#46]
When using code completion for a tag snippet by typing <cfsometag, the snippet inserts a superflous bracket character < before the tag. So either one has to get used to leaving off the leading bracket when typing the beginning of the tag or you'd have to jump back to the start of the tag in order to delete the superflous bracket.

If I type <cfso and use code completion for <cfsometag, I'd expect the snippet it to complete this to exactly this <cfsometag, not to <<cfsometag.

Is there some setting that I may have missed that would rectify this?

Anyway, thank you very much indeed for this great atom package, we're finally able to ditch Dreamweaver for development!

**Comment by tollus** [comment]
When you use the code completion you don't want to write the original <. For example, you just want to write `cfset` then choose the snippet, and you'll see it changes the `cfset` to `<cfset | = >` (where `|` is where the cursor is)

**Comment by philcruz** [comment]
Typing the opening bracket is a common way to start code completion, well, at least with CFEclipse. So it will be a smoother transition for such folks. +1 for Atom supporting this.

**Comment by rwatts3** [comment]
This package could check if the first character is < then replace it when the snippet is embedded.

**Comment by andrew-dixon** [comment]
I think it actually needs the package upgraded to use Atom's autocomplete-plus as ATM it is just inserting snippets and not auto-completing as such.

**Comment by KrunchMuffin** [comment]
I agree with @andrew-dixon plus it's a PITA removing superfluous code that gets inserted. I am still using sublime 3 because of this. Would love to switch to Atom.

**Comment by zoo1** [comment]
I resolved this issue in my CFML autocomplete package, you can find it [here](https://atom.io/packages/autocomplete-cfml)

**Comment by dnando** [comment]
Couldn't find auto-complete plus in the Atom package search, but then
looking at the github repository I saw that you don't have to install it -
included with Atom.

I just installed CFML autocomplete, tried it and still seeing

<<cfset  = >

:-(



Aria Media Sagl
+41 (0)76 303 4477 cell
skype: ariamedia

**Comment by zoo1** [comment]
@dnando make sure you are selecting that auto-complete tag part of autocomplete CFML to insert and not the snippets included in this package. 
The autocomplete included should look like the image below. The red elements are autocomplete added.
![cfset](https://cloud.githubusercontent.com/assets/4008169/20228438/1ed9538c-a81f-11e6-89a1-79fd90fd9fc9.gif)

**Comment by zoo1** [comment]
@dnando sorry for the confusion, I just published a fix for this. If you have any other issues feel free to open them on the autocomplete repo. I'm closing this ticket as this functionality will not be added by this language package.

**Comment by dnando** [comment]
Ah, I see what's happening.

If I type <cf and then choose from the dropdown, remaining within the
choices that have red brackets, it works.

[image: Inline image 2]

If I type <cfs, it jumps down into the green tab choices and then what is
inserted is a double bracket to start, as below:

[image: Inline image 1]

The behavior is different if one remembers to *not* type the initial
opening bracket. Then it works as you've shown in your screenshot.

The << issue occurs if the opening bracket is typed.

Thanks for doing this. I like it.



Aria Media Sagl
+41 (0)76 303 4477 cell
skype: ariamedia

**Comment by zoo1** [comment]
@dnando  <cfs should work in the version I just pushed out.
