### ISSUE TITLE
half of "cfsetting" highlights

### ISSUE THREAD

**Issue by ArtskydJ** [atuttle/atom-language-cfml#47]
![capture](https://cloud.githubusercontent.com/assets/1833684/8882963/eee063c6-3210-11e5-800b-07fb713185b8.PNG)

**Comment by atuttle** [comment]
I wonder if this is due to a sorted list of keywords, where cfsetting would need to come before cfset so that it could match first. I've seen the same problem with no/not, too.

**Comment by tollus** [comment]
What about adding a `\b` to the end of the capture or whitespace? so it needs to match completely?

`'begin': '(<)((?i:(cfset)\\b))'`

**Comment by dajester2013** [comment]
@tollus I tried that locally, seems to correct the issue for me.

**Comment by atuttle** [comment]
```
apm publish patch
Preparing and tagging a new version ✓
Pushing v0.8.8 tag ✓
Publishing language-cfml@v0.8.8 ✓
```

New version published. Please report back whether or not this resolved the bug for you. :)

**Comment by ArtskydJ** [comment]
Fixed!
