### ISSUE TITLE
color coded operator text

### ISSUE THREAD

**Issue by KevinMcCoy** [atuttle/atom-language-cfml#48]
AND, OR  -> will show me color coded, however 
EQ, NOT, IS  -> dosen't

**Comment by dajester2013** [comment]
Oddly, I get the exact opposite.

Looking at [cfscript.cson L77](https://github.com/atuttle/atom-language-cfml/blob/master/grammars/cfscript.cson#L77), the last 3 operators are scoped to keyword.operator.cfml, while the first two are not.

I think what is happening is the first two keywords are taking whatever scope is applied to the cfml tag they are in, whereas the other 3 are getting the scope from cfscript.cson, which is not recognized by your theme.

The AND/OR keywords need to be added to that list, and perhaps keywords can be dual-scoped to something that more themes would support.

**Comment by elpete** [comment]
Fixed in 0.12
