### ISSUE TITLE
Syntax Highlighting breaks with <cfhttp>

### ISSUE THREAD

**Issue by mikoMK** [atuttle/atom-language-cfml#52]
If you include the protocol in the URL and use a CFML variable as parameter value, the highlighting breaks for the rest of the document. Everything is colored like a string except for the number signs.
When you remove either the protocol or the CFML variable, the highlighting works again.

### Example
![2015-07-30 13_26_13-test cfm - s__pro-alter_ch - atom](https://cloud.githubusercontent.com/assets/9440351/8982145/98eb839e-36be-11e5-9084-2ae1f5ae4457.png)

Atom version: 1.0.3
language-cfml version: 0.8.8

**Comment by dajester2013** [comment]
Can you try switching the grammar to CFML instead of HTML (CFML) and see if
that changes anything?

**Comment by kliakos** [comment]
I think it's the ## inside the string at the tag parameter that break the highlighting. I see this often.

**Comment by mikoMK** [comment]
@dajester2013 It doesn't matter, which grammar I use.

**Comment by rwatts3** [comment]
What's the solution to this. It's definitely when #" is existing. If I remove the # it works fine. Is there a quick place to fix this ?

**Comment by skiant** [comment]
More specifically, it's the double slash that seems to cause problems.

A single slash seems doesn't seem to create this kind of issue. I guess this has something to do with the regex patterns, might be a clash with the comments patterns ?

**Comment by rwatts3** [comment]
That's a god start it's definitely someone to do with the slash.  I've tested this and can confirm.

**Comment by elpete** [comment]
This is a bug when running the `language-hyperlink` package included by default in Atom.  A failing test case has been added to the project to make it easier to know how and when it is fixed.

**Comment by elpete** [comment]
[I've opened a pull request](https://github.com/atom/language-hyperlink/pull/5) on `language-hyperlink` that should fix our issue with url's here.

**Comment by elpete** [comment]
The pull request was accepted. Next version of atom should fix this issue! 👍

**Comment by skiant** [comment]
Great news, thanks a lot for your effort! :+1:

**Comment by mikoMK** [comment]
Thank you very much @elpete for the great work!
