### ISSUE TITLE
Syntax Highlight Issue

### ISSUE THREAD

**Issue by rwatts3** [atuttle/atom-language-cfml#55]
I'm seeing lots of syntax highlighting issues. Is there any fix for these coming soon ?

**Comment by rwatts3** [comment]
Any update on this issue ?

**Comment by elpete** [comment]
The best thing to do, if you can, is to write a failing test case for the issue you are seeing.  You can look at[ our own spec folder](https://github.com/atuttle/atom-language-cfml/tree/master/spec) for this and also on the [Atom documentation](https://atom.io/docs/v1.0.19/hacking-atom-writing-specs).  This will help those maintaining this package know precisely what is broken.

**Comment by atuttle** [comment]
Sorry, @rwatts3, I'm closing this as it's not specific at all. If you have a specific request, please do open more bugs. Even better if you can send a failing test case, as @elpete described.
