### ISSUE TITLE
Syntax highlighting after strings that contain fully qualified URLs and variable output pounds (##) are broken after recent update to 0.10.0

### ISSUE THREAD

**Issue by infernocloud** [atuttle/atom-language-cfml#59]
This seems complicated. Some combination of the doubled slashes in http:// and the output pounds (##). It almost seems like its trying to do some kind of URL highlighting but doing it wrong.

Test strings that causes syntax highlighting to break:
testUrl = "http://www.google.com/#test#";
testUrl = "http://www.google.com/test#";

These strings do not break syntax highlighting:
testUrl = "http:/www.google.com/#test#";
testUrl = "http//www.google.com/#test#";
testUrl = "http://www.google.com/#test";

**Comment by atuttle** [comment]
@elpete could this be related to your PR for https://github.com/atom/language-hyperlink/pull/5 ?

**Comment by infernocloud** [comment]
Oh interesting I didn't even think it could have been affected by another package. I disabled that package and syntax highlighting is working correctly. Should we close this issue here?

**Comment by atuttle** [comment]
No, let's leave this open for now, as that PR was submitted specifically to fix another bug (probably a simpler form of this one) in this project.

**Comment by elpete** [comment]
It sure sounds like it. 

@infernocloud, are you sure this was working in prior versions of this package, or could it be you just noticed it at this time?

**Comment by infernocloud** [comment]
I'm sorry, I didn't get notified about these messages. Yes I'm sure syntax highlighting was correctly working before I updated packages in Atom.

**Comment by elpete** [comment]
Interesting...it seems that the initial bug was noticed between v0.8.6 and v0.8.7 when the `embedded-cf` rule was added.  Before that, they just looked like strings.

@infernocloud, do you know what version you updated from?  Or can you verify that there was no embedded syntax highlighting before (but neither was it incorrectly highlighting strings)?

I just want to make sure we're fixing this in the right place.

**Comment by atuttle** [comment]
ping @infernocloud

**Comment by elpete** [comment]
Regardless of when the issue was introduced, I think this issue should be fixed with @tollus [pull request over on `language-hyperlink`](https://github.com/atom/language-hyperlink/pull/6).

We'll leave this issue open until that pull request is merged.

**Comment by dnando** [comment]
I'm seeing syntax highlighting breaking down whenever a single # character is used, for instance with a jQuery selector. This seems to have started after I updated to the lastest version (0.11.0).

**Comment by scottyinzeo** [comment]
noticing the same thing @dnando ... I'm also noticing that there are now two HTML (CFML) entries available when opening the syntax picker.

**Comment by elpete** [comment]
@scottyinzeo The duplicate HTML (CFML) entries are just a naming issue in the new injection grammar.  That will be fixed in the next release.  Sorry.

**Comment by elpete** [comment]
@dnando Fix for this should be in the next version.  (Just pushed it up.)

**Comment by elpete** [comment]
Fixed in 0.12
