### ISSUE TITLE
Function names are not color coded

### ISSUE THREAD

**Issue by redtopia** [atuttle/atom-language-cfml#68]
I'm not seeing any color coding for function names.

![image](https://cloud.githubusercontent.com/assets/812777/11608829/09a8a4e0-9b32-11e5-9ff3-3f20cab35d72.png)

**Comment by elpete** [comment]
@redtopia, I'm having trouble reproducing this.

Can you specify:
Atom Version:
atom-language-cfml version:
Current grammar (bottom right corner):

Thanks!

**Comment by redtopia** [comment]
Atom 1.2.4 (Windows 7)
How do I find out the atom-language-cfml version?
Current grammar: HTML (CFML)

Also, the grammar is set to auto-detect, and it's picking HTML (CFML) when I open a .cfc file, written completely in cfscript.

**Comment by elpete** [comment]
You can find package versions by going to `Preferences` -> `Packages` and search for `atom-language-cfml`

**Comment by redtopia** [comment]
I'm running 0.10.0

![image](https://cloud.githubusercontent.com/assets/812777/12208536/97a4e464-b60a-11e5-8f52-db32f0f5d8da.png)

**Comment by elpete** [comment]
Fixed in 0.12
