### ISSUE TITLE
Backslash in string literal as a function argument confuses highlighter

### ISSUE THREAD

**Issue by ArtskydJ** [atuttle/atom-language-cfml#74]
The syntax highlighter is getting confused on backslashes in string literals that are function parameters. The string with the backslash can be defined as a variable outside the function call, so there's an easy work-around.

![capture](https://cloud.githubusercontent.com/assets/1833684/12521500/9239afda-c110-11e5-8519-4038028fcee0.PNG)

Similar to #27.
Using v0.11.0.

Thanks for all the work that you maintainers put into this package! It really helps me out with my work!

**Comment by ArtskydJ** [comment]
Depending on how much time I have, I might be able to make a PR for the tests at least.

This isn't a show stopper, because I'm able to define `backslash` in its own variable.

**Comment by elpete** [comment]
Fixed in 0.12
