### ISSUE TITLE
Single quote confuses highlighting after it. 

### ISSUE THREAD

**Issue by lramirez925** [atuttle/atom-language-cfml#75]
![image](https://cloud.githubusercontent.com/assets/15653933/12618514/23e6ad96-c4e2-11e5-983f-b0789eb20b1b.png)

Adding the above code snippet to a cfc file (haven't tested but I expect cfml also ) breaks highlighting after the test until another single quote is found. Removing the single quote from the listQualify's second parameter fixes the issue. Seems to be an issue with adding the js class and the invalid class. 

I tried to shrink the code to be as simple as possible to show the issue so I removed the rest of the HQL.

**Comment by lramirez925** [comment]
May be related to issue https://github.com/atuttle/atom-language-cfml/issues/74

**Comment by simonbingham** [comment]
I've seen the same issue with single quotes in comments.

![screen shot 2016-02-18 at 10 36 39](https://cloud.githubusercontent.com/assets/1306644/13140720/9daa286a-d62b-11e5-9b54-f87d7a4224b8.png)

**Comment by elpete** [comment]
Fixed in 0.12
