### ISSUE TITLE
This package is affecting non-CF language files

### ISSUE THREAD

**Issue by infernocloud** [atuttle/atom-language-cfml#79]
As an example, I'm working in a HTML (Mustache) file (.hbs).The CFML plug-in is injecting CFML classes and breaking syntax coloring even in non-CFML files.

I've verified that it is this package by disabling it and seeing normal syntax highlighting work in this file.

Here is a screenshot:
https://onedrive.live.com/redir?resid=91F7060A4D6A37E4!162&authkey=!ANXoBcj86l4FqnY&v=3&ithint=photo%2cpng

Is there any other information that would help troubleshoot this?

**Comment by elpete** [comment]
Fixed in 0.12.
