### ISSUE TITLE
Syntax highlighting after the hash character

### ISSUE THREAD

**Issue by marty80** [atuttle/atom-language-cfml#83]
The syntax highlighting stops working after the hash character, but it shouldn't.

![screenshot](https://cloud.githubusercontent.com/assets/6063495/14667029/72f51de0-070f-11e6-8177-ec83712a7f91.png)

**Comment by thecfguy** [comment]
Similar issue with string has // and variable with # sign,
```
<cfset myurl = "http://localsite.com/q=#variables.query#">
```

**Comment by willthemoor** [comment]
Came to report something similar. Think it might have something to do with the scope within `cfoutput` tags. 

![image](https://cloud.githubusercontent.com/assets/54206/18360571/642b990c-75b3-11e6-9ce2-cc023f8029c7.png)


```html
<a href="foo.html#anchor">Link text</a>
<p> Working <em>fine</em>.</p>

<a href="http://blah.cc/foo.html#anchor">Link text</a>
<p> Working <em>fine</em>.</p>

<a href="https://blah.cc/my.cfm?paramid=#get_current_paramID()#">Link text</a>
<p>
  This text is fine. The scope |here| is:
   text.html.cfml
</p>

<cfoutput>
<a href="https://blah.cc/my.cfm?paramid=#get_current_paramID()#">Link text</a>
<p>
  This text and tag have the same highlighting as a string. The scope |here| is:

  text.html.cfml
  meta.scope.cfoutput.cfml
  meta.tag.inline.any.html
  string.quoted.double.html
  string.quoted.double.cfml

</p>
</cfoutput> <!-- Hey, that works -->

<p> Still broken here though! The scope |here| is:
  text.html.cfml
  meta.scope.cfoutput.cfml
  meta.tag.inline.any.html
  string.quoted.double.html
  string.quoted.double.cfml
</p>

```

I poked around the source but couldn't make heads or tails of the what/why. Hope this helps someone with a bigger brain than me.

**Comment by Mootly** [comment]
I am getting this too:

Breaks: `<li><a href="mailto:#application.emailHelp#">Contact Support</a></li>`
Correct: `<li><a href="mailto&##58;#application.emailHelp#">Contact Support</a></li>`

Removing the cfoutput block does indeed fix the color coding, as does moving it directly into the string.

Add that to the stuff above, and it looks like the syntax highlighter does not like hash marks after certain bits of punctuation when inside a cfoutput block.

**Comment by dnando** [comment]
I'm seeing a similar issue where both syntax highlighting and code completion is breaking after an & in the query string of an a href tag. See attached screenshot.

![screen shot 2016-11-21 at 14 57](https://cloud.githubusercontent.com/assets/554655/20485358/74bb263e-affb-11e6-9a56-d90e2dd9750e.gif)

**Comment by Mootly** [comment]
The color coding starting at the ampersand may be complicated by any error or validation parsing you have. Mine flags them as needing to be escaped to &amp;. Could certainly be some contention adding to the wonkiness.
