### ISSUE TITLE
Using CTRL+CMD+Down Arrow to move code down results in an error sound

### ISSUE THREAD

**Issue by simonbingham** [atuttle/atom-language-cfml#91]
Using `CTRL`+`CMD`+`Down Arrow` to move selected code down results in an error sound. These's no sound when moving code up. I don't think there should be a sound.

**Comment by zoo1** [comment]
@simonbingham I agree with you, that functionality seems inconsistent and buggy. However, this package doesn't effect the behavior of the moving selected text quick-keys. I would suggest opening an issue [here](https://github.com/atom/atom/issues).

**Comment by simonbingham** [comment]
Oops. Good point. I'll open the issue there instead.
