### ISSUE TITLE
Different code coloring for CFML tags vs. HTML

### ISSUE THREAD

**Issue by yacoubean** [atuttle/atom-language-cfml#92]
One thing I love about CFBuilder is that CFML tags are a different color from HTML. It makes it very easy to pick out a CFML tag buried in a pile of HTML. Is this possible with atom-language-cfml? Is this something I can configure (or code) myself?

**Comment by seybsen** [comment]
You can customize everything yourself:

just hit <kbd>cmd</kbd>+<kbd>option</kbd>+<kbd>i</kbd> (on mac) to open the devtools like in chrome and inspect a CFML tag (that's `span.entity.name.tag.cfml`)

Then open the global atom Stylesheet "Atom" -> "Stylesheet" (on mac).

Then add:

```
atom-text-editor::shadow {
  .entity.name.tag.cfml {
    color: #9accdf; /* your color of choice */
   }
}
```

**Comment by yacoubean** [comment]
Very cool! Thanks a ton Sebastian! :)
